spring:
  profiles:
    active: dev  # default, overridden by SPRING_PROFILES_ACTIVE env var
  datasource:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  output:
    ansi:
     enabled: always

management:
  endpoints:
    web:
      exposure:
        include: health,info

#Use SPRING_PROFILES_ACTIVE=prod when deploying production.