name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Step 3: Build and run tests with JaCoCo coverage
      - name: Build and verify
        run: mvn -B clean verify

      # Step 4: Build Docker image
      - name: Build Docker image
        run: docker build -t library-api .

      # Step 5 (Optional): List Docker images (for verification)
      - name: List Docker images
        run: docker images | grep library-api

      # Step 6: Upload JaCoCo report as build artifact
      - name: Upload JaCoCo report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: target/site/jacoco/
