name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Step 3: Build with Maven
      - name: Build with Maven
        run: mvn clean package -DskipTests

      # Step 4: Build Docker image
      - name: Build Docker image
        run: docker build -t library-api .

      # Step 5 (Optional): Test image
      - name: List Docker images
        run: docker images | grep library-api
